### ISSUE TITLE
Questions on testing TMNet

### ISSUE THREAD

**Issue by zychen-ustc** [CS-GangXu/TMNet#8]
Hi! I'm testing TMNet for interpolating multiple frames on some video datasets and find the results really strange: I aim to **interpolate 7 frames** between two known frames. When I set the **input frame number to 2**, the result looks good. However, when I set the **input frame number to 4**, the results seem to suffer from some unknown noise. I put one example below. The first image is the result of 2 input and the second image is the result of 4 input (Note that in this example the color channel is reversed, but I have corrected it and the problem still exists). I did some further testing and find that when I interpolate less frames(1, 3), the noise disappears. Do you know some possible reasons? Thanks a lot!
![3](https://user-images.githubusercontent.com/53959668/140016808-ef672936-7153-4ce9-99b2-e8b38dae8e9c.jpg)
![3](https://user-images.githubusercontent.com/53959668/140016814-812391b8-67f4-4dd9-83a2-81b171c1c473.jpg)

**Comment by CS-GangXu** [comment]
Sorry for the late reply @zychen-ustc, firstly I want to check if my understanding is right:
A: Input -7 output - Input
B: Input -7 output - Input -7 output - Input -7 output - Input
In the training process in the original paper, we only input 2 frames to train the network for interpolating multiple frames between two adjacent frames.
Thus, when the length of the whole sequence of frames gets longer, there may exist misalignment caused by the Deformable Convolution and it will be spread by Bi-directional Deformable ConvLSTM among the whole sequence of frames, resulting the artifact.

**Comment by zychen-ustc** [comment]
Thanks for your reply! I thought the input frame number is 4 during the whole training process before. If the training on multiple frames only uses two frames as model input, it is reasonable that four input frames could lead to some unknown problems.
